spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.10:3306/gulimall_ums?useSSL=false
    username: root
    password: root

  application:
    name: gulimall-coupon

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  # mapper-locations: classpath*:/mapper/**/*.xml

  # 数据自增
  global-config:
    db-config:
      id-type: auto

